import TheSilentEcho from "../../Assets/Images/DashboardTabImages/TheSilentEcho.jpg";
import TheMysteryOfTime from "../../Assets/Images/DashboardTabImages/TheMysteryOfTime.jpg";
import TheScienceOfTomorrow from "../../Assets/Images/DashboardTabImages/TheScienceOfTomorrow.jpg";
import TheLoveAcrossTime from "../../Assets/Images/DashboardTabImages/TheLoveAcrossTime.jpg";
import JounrneyToTheUnknown from "../../Assets/Images/DashboardTabImages/JounrneyToTheUnknown.jpg";
import MemoriesOfTheLegend from "../../Assets/Images/DashboardTabImages/MemoriesOfTheLegend.jpg";
import TheHountedForest from "../../Assets/Images/DashboardTabImages/TheHountedForest.jpg";
import TechEvolution from "../../Assets/Images/DashboardTabImages/TechEvolution.jpg";
import HiddenKingdom from "../../Assets/Images/DashboardTabImages/HiddenKingdom.jpg";
import HopesAndFears from "../../Assets/Images/DashboardTabImages/HopesAndFears.jpg";
import RisingStars from "../../Assets/Images/DashboardTabImages/RisingStars.jpg";
import BeyondTheHorizon from "../../Assets/Images/DashboardTabImages/BeyondTheHorizon.jpg";
import TheLastHope from "../../Assets/Images/DashboardTabImages/TheLastHope.jpg";
import WhisperOfThePast from "../../Assets/Images/DashboardTabImages/WhisperOfThePast.jpg";
import TheBookOfShadows from "../../Assets/Images/DashboardTabImages/TheBookOfShadows.jpg";
import ChasingDreams from "../../Assets/Images/DashboardTabImages/ChasingDreams.jpg";
import TheLastGoodBye from "../../Assets/Images/DashboardTabImages/TheLastGoodBye.jpg";
import UnSpokenTruth from "../../Assets/Images/DashboardTabImages/UnSpokenTruth.jpg";
import TheArtOfWar from "../../Assets/Images/DashboardTabImages/TheArtOfWar.jpg";
import TimeLessLove from "../../Assets/Images/DashboardTabImages/TimeLessLove.png";
import HarryPotter from "../../Assets/Images/DashboardTabImages/HarryPotter.jpg";
import InTheShadows from "../../Assets/Images/DashboardTabImages/InTheShadows.jpg";
import SilentWaters from "../../Assets/Images/DashboardTabImages/SilentWaters.jpg";
import TheEscape from "../../Assets/Images/DashboardTabImages/TheEscape.jpg";
import MindsUnLeashed from "../../Assets/Images/DashboardTabImages/MindsUnLeashed.jpg";
import TheSilentWitness from "../../Assets/Images/DashboardTabImages/TheSilentWitness.jpg";
import ShatteredDreams from "../../Assets/Images/DashboardTabImages/ShatteredDreams.jpg";
import TheFateWeb from "../../Assets/Images/DashboardTabImages/TheFateWeb.jpg";
import TheInfiniteJourney from "../../Assets/Images/DashboardTabImages/TheInfiniteJourney.jpg";
import TheGhostOfTheFuture from "../../Assets/Images/DashboardTabImages/TheGhostOfTheFuture.jpg";
import TheLastRevolution from "../../Assets/Images/DashboardTabImages/TheLastRevolution.jpg";
import TheWarriorsPath from "../../Assets/Images/DashboardTabImages/TheWarriorsPath.jpg";
import TheBlackSwan from "../../Assets/Images/DashboardTabImages/TheBlackSwan.jpg";
import TalesFromTheDeep from "../../Assets/Images/DashboardTabImages/TalesFromTheDeep.jpg";
import TheEnchantedRealm from "../../Assets/Images/DashboardTabImages/TheEnchantedRealm.jpg";

export const BookData = {
  currentPage: 1,
  totalPages: 7,
  totalItems: 35,
  itemsPerPage: 5,
  data: [
    {
      id: 1,
      name: "The Silent Echo",
      author: "John Smith",
      genre: "Fiction",
      category: "Premium",
      publication_year: 2024,
      publisher: "Penguin Books",
      rating: 8.7,
      img: TheSilentEcho,
    },
    {
      id: 2,
      name: "The Mystery of Time",
      author: "Jane Doe",
      genre: "Mystery",
      category: "Free",
      publication_year: 2023,
      publisher: "HarperCollins",
      rating: 9.2,
      img: TheMysteryOfTime,
    },
    {
      id: 3,
      name: "The Science of Tomorrow",
      author: "Dr. Michael Brown",
      genre: "Scientific",
      category: "Premium",
      publication_year: 2023,
      publisher: "Oxford University Press",
      rating: 9.0,
      img: TheScienceOfTomorrow,
    },
    {
      id: 4,
      name: "Love Across Time",
      author: "Emily Green",
      genre: "Romance",
      category: "Free",
      publication_year: 2024,
      publisher: "Random House",
      rating: 8.3,
      img: TheLoveAcrossTime,
    },
    {
      id: 5,
      name: "Journey to the Unknown",
      author: "Christopher Lee",
      genre: "Adventure",
      category: "Premium",
      publication_year: 2024,
      publisher: "Viking Press",
      rating: 8.5,
      img: JounrneyToTheUnknown,
    },
    {
      id: 6,
      name: "Memoirs of a Legend",
      author: "Sarah Collins",
      genre: "Biography",
      category: "Free",
      publication_year: 2022,
      publisher: "Simon & Schuster",
      rating: 7.8,
      img: MemoriesOfTheLegend,
    },
    {
      id: 7,
      name: "The Haunted Forest",
      author: "William Black",
      genre: "Horror",
      category: "Premium",
      publication_year: 2021,
      publisher: "Wiley",
      rating: 7.2,
      img: TheHountedForest,
    },
    {
      id: 8,
      name: "Tech Evolution",
      author: "Sarah Johnson",
      genre: "Scientific",
      category: "Free",
      publication_year: 2023,
      publisher: "Pearson",
      rating: 8.1,
      img: TechEvolution,
    },
    {
      id: 9,
      name: "The Hidden Kingdom",
      author: "David Carter",
      genre: "Fantasy",
      category: "Premium",
      publication_year: 2024,
      publisher: "Macmillan",
      rating: 9.3,
      img: HiddenKingdom,
    },
    {
      id: 10,
      name: "Fears and Hopes",
      author: "Olivia White",
      genre: "Thriller",
      category: "Free",
      publication_year: 2024,
      publisher: "HarperCollins",
      rating: 8.4,
      img: HopesAndFears,
    },
    {
      id: 11,
      name: "Rising Stars",
      author: "Alex Brown",
      genre: "Young Adult",
      category: "Premium",
      publication_year: 2024,
      publisher: "Delacorte Press",
      rating: 9.0,
      img: RisingStars,
    },
    {
      id: 12,
      name: "Beyond the Horizon",
      author: "Rachel Grey",
      genre: "Adventure",
      category: "Free",
      publication_year: 2023,
      publisher: "St. Martin's Press",
      rating: 7.6,
      img: BeyondTheHorizon,
    },
    {
      id: 13,
      name: "The Last Hope",
      author: "Michael Taylor",
      genre: "Science Fiction",
      category: "Premium",
      publication_year: 2023,
      publisher: "Tor Books",
      rating: 8.8,
      img: TheLastHope,
    },
    {
      id: 14,
      name: "Whispers of the Past",
      author: "Anna White",
      genre: "Historical Fiction",
      category: "Free",
      publication_year: 2022,
      publisher: "Doubleday",
      rating: 8.2,
      img: WhisperOfThePast,
    },
    {
      id: 15,
      name: "The Book of Shadows",
      author: "Benjamin Walker",
      genre: "Fantasy",
      category: "Premium",
      publication_year: 2024,
      publisher: "Bloomsbury",
      rating: 9.1,
      img: TheBookOfShadows,
    },
    {
      id: 16,
      name: "Chasing Dreams",
      author: "Sophia Harris",
      genre: "Self Help",
      category: "Free",
      publication_year: 2024,
      publisher: "TarcherPerigee",
      rating: 8.5,
      img: ChasingDreams,
    },
    {
      id: 17,
      name: "The Last Goodbye",
      author: "Daniel King",
      genre: "Romance",
      category: "Premium",
      publication_year: 2024,
      publisher: "Hachette Books",
      rating: 7.9,
      img: TheLastGoodBye,
    },
    {
      id: 18,
      name: "Unspoken Truths",
      author: "Julia Carter",
      genre: "Thriller",
      category: "Free",
      publication_year: 2023,
      publisher: "Penguin Random House",
      rating: 8.0,
      img: UnSpokenTruth,
    },
    {
      id: 19,
      name: "The Art of War",
      author: "Sun Tzu",
      genre: "History",
      category: "Premium",
      publication_year: 2020,
      publisher: "The Modern Library",
      rating: 9.4,
      img: TheArtOfWar,
    },
    {
      id: 20,
      name: "Timeless Love",
      author: "Margaret Sullivan",
      genre: "Romance",
      category: "Free",
      publication_year: 2024,
      publisher: "Grand Central Publishing",
      rating: 8.3,
      img: TimeLessLove,
    },
    {
      id: 21,
      name: "Harry Potter",
      author: "J.K. Rowling",
      genre: "Fantasy",
      category: "Premium",
      publication_year: 1997,
      publisher: "Scholastic",
      rating: 10,
      img: HarryPotter,
    },
    {
      id: 22,
      name: "In the Shadows",
      author: "Olivia Wright",
      genre: "Mystery",
      category: "Free",
      publication_year: 2023,
      publisher: "William Morrow",
      rating: 7.5,
      img: InTheShadows,
    },
    {
      id: 23,
      name: "Silent Waters",
      author: "Edward Black",
      genre: "Fiction",
      category: "Premium",
      publication_year: 2023,
      publisher: "Knopf Doubleday",
      rating: 8.0,
      img: SilentWaters,
    },
    {
      id: 24,
      name: "The Escape",
      author: "Sarah Montgomery",
      genre: "Adventure",
      category: "Free",
      publication_year: 2024,
      publisher: "Little, Brown and Company",
      rating: 8.6,
      img: TheEscape,
    },
    {
      id: 25,
      name: "Minds Unleashed",
      author: "Victor Harris",
      genre: "Self Help",
      category: "Premium",
      publication_year: 2024,
      publisher: "HarperOne",
      rating: 8.2,
      img: MindsUnLeashed,
    },
    {
      id: 26,
      name: "The Silent Witness",
      author: "Jessica Lee",
      genre: "Thriller",
      category: "Free",
      publication_year: 2023,
      publisher: "Blackstone Publishing",
      rating: 8.4,
      img: TheSilentWitness,
    },
    {
      id: 27,
      name: "Shattered Dreams",
      author: "David Harris",
      genre: "Fiction",
      category: "Premium",
      publication_year: 2022,
      publisher: "Vintage",
      rating: 8.1,
      img: ShatteredDreams,
    },
    {
      id: 28,
      name: "Fate's Web",
      author: "Lucas Evans",
      genre: "Fantasy",
      category: "Free",
      publication_year: 2023,
      publisher: "Orbit Books",
      rating: 7.9,
      img: TheFateWeb,
    },
    {
      id: 29,
      name: "The Infinite Journey",
      author: "Alice Stewart",
      genre: "Adventure",
      category: "Premium",
      publication_year: 2023,
      publisher: "Crown Publishing",
      rating: 9.0,
      img: TheInfiniteJourney,
    },
    {
      id: 30,
      name: "Ghosts of the Future",
      author: "Zoe Carter",
      genre: "Horror",
      category: "Free",
      publication_year: 2024,
      publisher: "Macmillan",
      rating: 7.4,
      img: TheGhostOfTheFuture,
    },
    {
      id: 31,
      name: "The Last Revolution",
      author: "Henry Adams",
      genre: "History",
      category: "Premium",
      publication_year: 2023,
      publisher: "W.W. Norton & Company",
      rating: 9.3,
      img: TheLastRevolution,
    },
    {
      id: 32,
      name: "Warrior's Path",
      author: "James Marshall",
      genre: "Adventure",
      category: "Free",
      publication_year: 2024,
      publisher: "Greenleaf Book Group",
      rating: 7.7,
      img: TheWarriorsPath,
    },
    {
      id: 33,
      name: "The Black Swan",
      author: "Nassim Taleb",
      genre: "Scientific",
      category: "Premium",
      publication_year: 2020,
      publisher: "Random House",
      rating: 8.9,
      img: TheBlackSwan,
    },
    {
      id: 34,
      name: "Tales of the Deep",
      author: "Charlotte King",
      genre: "Mystery",
      category: "Free",
      publication_year: 2023,
      publisher: "Penguin Books",
      rating: 8.2,
      img: TalesFromTheDeep,
    },
    {
      id: 35,
      name: "The Enchanted Realm",
      author: "George Milton",
      genre: "Fantasy",
      category: "Premium",
      publication_year: 2023,
      publisher: "Tor Books",
      rating: 8.8,
      img: TheEnchantedRealm,
    },
  ],
};


