services:
  db:
    image: mysql:8.4.4
    container_name: drupal_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookmanagerapp
      MYSQL_USER: kratia
      MYSQL_PASSWORD: krati@321
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - drupal_network

  drupal:
    image: drupal:11
    container_name: drupal
    ports:
      - "8083:80"
    environment:
      DRUPAL_DB_HOST: db
      DRUPAL_DB_NAME: bookmanagerapp
      DRUPAL_DB_USER: kratia
      DRUPAL_DB_PASSWORD: krati@321
    volumes:
      - drupal_data:/var/www/html
    depends_on:
      - db
    networks:
      - drupal_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: drupal_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: kratia
      PMA_PASSWORD: krati@321
    depends_on:
      - db
    networks:
      - drupal_network

networks:
  drupal_network:
    driver: bridge

volumes:
  db_data:
  drupal_data:
